DROP TABLE IF EXISTS PUBLIC.BOOK;

CREATE TABLE PUBLIC.BOOK_DESCRIPTION (
  ID integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  TITLE VARCHAR(255) NOT NULL,
  AUTHOR VARCHAR(255) NOT NULL,
  GENRE VARCHAR(255) NOT NULL,
  BOOK_ID INTEGER NOT NULL UNIQUE,
  CONSTRAINT BOOK_DESCRIPTION_PRIMARY_KEY PRIMARY KEY (ID)
);
CREATE TABLE PUBLIC.BOOK (
  ID integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  NAME_BOOK VARCHAR(255) NOT NULL,
  UUID DEFAULT uuid_generate_v4 (),
  BOOK_ID INTEGER NOT NULL UNIQUE,
  CONSTRAINT BOOK_PRIMARY_KEY PRIMARY KEY (ID),
  CONSTRAINT BOOK_FOREIGN_KEY FOREIGN KEY (BOOK_ID) REFERENCES BOOK_DESCRIPTION (ID)
);
