DROP TABLE IF EXISTS PUBLIC.BOOK;

CREATE TABLE PUBLIC.BOOK (
  ID         INTEGER      NOT NULL AUTO_INCREMENT,
  NAME_BOOK       VARCHAR(255) NOT NULL,
  YEARS INTEGER(4)   NOT NULL,
  AUTHOR       VARCHAR(255) NOT NULL,
  CONSTRAINT BOOK_DESCRIPTION PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.BOOK_DESCRIPTION (
  ID          INTEGER      NOT NULL AUTO_INCREMENT,
  GENRE VARCHAR(255) NOT NULL,
  BOOK_ID     INTEGER      NOT NULL UNIQUE,
  CONSTRAINT BOOK_DESCRIPTION_PRIMARY_KEY PRIMARY KEY (ID),
  CONSTRAINT BOOK_FOREIGN_KEY FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);